### ISSUE TITLE
tfh pushvars includes quotes

### ISSUE THREAD

**Issue by voycey** [hashicorp-community/tf-helper#34]
So it seems like tfh is currently escaping quotes as part of its process, this means it is inserting variables into terraform cloud like `"false"` rather than just in raw text.

e.g.

`Creating default_firewall type:terraform hcl:false sensitive:false value:\"false\"`

In the pullvars command it is pulling the var as 

`default_firewall = "false"`

**Comment by fprimex** [comment]
Hi @voycey ,

My notification actually went to my spam folder, so I'll be fixing that :(

What you are looking for is `-hcl-var` rather than `-var`. The `-var` flag is for string variables. The `-hcl-var` will tick the `hcl` box and cause the string in the box to be interpreted as HCL. This way, `"false"` will become actual HCL `false.

```
$ tfh pushvars -hcl-var default_firewall=false -overwrite default_firewall
Updating default_firewall type:terraform hcl:true sensitive:false value:false

$ tfh pullvars
default_firewall = false
```

Give this a try and let me know if it's what you are after.

Cheers,

Brent W.
